sudo: require
language: generic
services:
  - docker

before_install:
  - docker build -t fernandovarella/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true fernandovarella/docker-react npm run test