version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes: 
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  
    command: ["npm", "run", "test"]